### ISSUE TITLE
Traduction seulement du WCF

### ISSUE THREAD

**Issue by CaribeSoy** [GeGeek/WBB-Translation#2]
Salut, est-ce que tu pourrais s'il te plaît "upload" (télécharger?) seulement le fichier correspondant au WCF sans les variables du forum? Merci d'avance :)

**Comment by GeGeek** [comment]
Bonjour,

je suis désolé, cela n'est pas possible car cela nécessite beaucoup de travail.
La traduction a été effectuée en exportant un fichier langue complet donc toutes les variables sont plus ou moins mélangées.
